"""
Generate adviser-ready PDF transition report (portrait, Auour branding).
Uses ReportLab for layout, tables, charts, and pagination.
All dimensions in points (1 inch = 72 pt).

Visual design matches files/Transition Report.dc.html (navy/brass palette,
Newsreader + Libre Franklin typography, cover page, allocation bars).
"""
from __future__ import annotations

from io import BytesIO
from decimal import Decimal
from typing import List, Dict, Any, Optional, Tuple
from datetime import date
from collections import defaultdict
from pathlib import Path
from xml.sax.saxutils import escape

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
    Flowable,
    HRFlowable,
)
from reportlab.lib.enums import TA_LEFT, TA_RIGHT
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

# ---------------------------------------------------------------------------
# Brand tokens (from files/README.md / Transition Report.dc.html)
# ---------------------------------------------------------------------------
AUOUR_NAVY = colors.HexColor("#0C2340")
AUOUR_NAVY_MUTED = colors.HexColor("#3A4A5F")
AUOUR_NAVY_SOFT = colors.HexColor("#243B54")
AUOUR_BRASS = colors.HexColor("#A9773F")
AUOUR_GREEN = colors.HexColor("#2F6B4F")
AUOUR_RED = colors.HexColor("#B23A2E")
AUOUR_GRAY = colors.HexColor("#8A93A0")
AUOUR_GRAY_MID = colors.HexColor("#6B7688")
AUOUR_SUBTOTAL_BG = colors.HexColor("#EEF1F6")
AUOUR_STAT_TINT = colors.HexColor("#F5F7FA")
AUOUR_TRACK = colors.HexColor("#F0F2F6")
AUOUR_CALLOUT_BG = colors.HexColor("#FBF5EA")
AUOUR_CALLOUT_TEXT = colors.HexColor("#5C4A2E")
AUOUR_BORDER = colors.Color(12 / 255, 35 / 255, 64 / 255, alpha=0.14)
AUOUR_BORDER_STRONG = colors.Color(12 / 255, 35 / 255, 64 / 255, alpha=0.18)
AUOUR_ROW_RULE = colors.Color(12 / 255, 35 / 255, 64 / 255, alpha=0.08)

CHART_PALETTE = [
    colors.HexColor(c)
    for c in (
        "#0C2340",
        "#1E3F5F",
        "#2F587A",
        "#436F93",
        "#5987AC",
        "#7AA0C0",
        "#9CB8D2",
        "#BDD0E1",
        "#A9773F",
        "#C8A268",
        "#B23A2E",
    )
]

FOOTER_TEXT = "For Investment Professional Use Only. Not for distribution to the public."
# Calibrated to Transition Report Sample 7.9.26.pdf (0.7" margins).
PAGE_MARGIN = 0.7 * inch
CONTENT_WIDTH_PT = letter[0] - 2 * PAGE_MARGIN  # ~511.2
STAT_CARD_H = 108
STAT_CARD_GAP = 11.2
STAT_CARD_PAD = 12

THINGS_TO_NOTE = [
    (
        "Point-in-Time Estimate",
        "Figures and calculations reflect a snapshot as of the date of this analysis. "
        "Anticipated gain realization is an estimate and subject to fluctuation based on "
        "market movement, execution timing, and pricing changes prior to trade date.",
    ),
    (
        "Risk Priority Over Tax Efficiency",
        "A shift in market risk per our risk models may trigger a rebalance independent of "
        "this transition schedule, likely generating an additional taxable event. Principal "
        "protection supersedes tax minimization in all cases.",
    ),
    (
        "Prior Transactions Excluded",
        "YTD transactions executed prior to this transition are not reflected in these "
        "calculations. Actual client tax liability may exceed the estimate shown.",
    ),
    (
        "Share Class Illustrative Only",
        "Share classes displayed (e.g., A, C) are for illustrative purposes and do not "
        "reflect end-state holdings. Non-institutional share classes must be converted to "
        "institutional class prior to transition for advisory eligibility. Conversion is a "
        "non-taxable event.",
    ),
    (
        "Legacy Mutual Fund Distributions",
        "Where legacy mutual funds are held in place of preferred ETFs, clients may incur "
        "additional taxable distributions (e.g., capital gains, dividend, or income "
        "distributions) generated by the fund itself. These distributions are outside our "
        "control, are not reflected in this transition's estimated tax impact, and may "
        "result in tax liability beyond what is shown here.",
    ),
]

ADDITIONAL_DISCLOSURES = (
    "This analysis is provided for informational purposes only and does not constitute tax "
    "or legal advice. Advisors should direct clients to consult their own tax or legal "
    "counsel regarding their specific situation. Estimated tax impact is derived from cost "
    "basis and holding period data as provided by custodian(s); accuracy is not independently "
    "verified, and discrepancies in custodial data will affect output. Short-term/long-term "
    "classification reflects holding period as of the analysis date and is subject to change "
    "if the transition timeline shifts. This output does not include and should not be "
    "construed as investment performance or return data. This analysis is hypothetical and "
    "for planning purposes only; it does not constitute a recommendation or reflect an "
    "executed transaction."
)

_FONTS_REGISTERED = False
_FONT_SERIF = "Helvetica"
_FONT_SERIF_MED = "Helvetica"
_FONT_SERIF_SEMI = "Helvetica-Bold"
_FONT_SERIF_ITALIC = "Helvetica-Oblique"
_FONT_SERIF_MED_ITALIC = "Helvetica-Oblique"
_FONT_SANS = "Helvetica"
_FONT_SANS_MED = "Helvetica"
_FONT_SANS_SEMI = "Helvetica-Bold"
_FONT_SANS_BOLD = "Helvetica-Bold"


def _register_fonts() -> None:
    """Register Newsreader + Libre Franklin; fall back to Helvetica if missing."""
    global _FONTS_REGISTERED
    global _FONT_SERIF, _FONT_SERIF_MED, _FONT_SERIF_SEMI, _FONT_SERIF_ITALIC, _FONT_SERIF_MED_ITALIC
    global _FONT_SANS, _FONT_SANS_MED, _FONT_SANS_SEMI, _FONT_SANS_BOLD
    if _FONTS_REGISTERED:
        return
    _FONTS_REGISTERED = True
    fonts_dir = Path(__file__).resolve().parent / "fonts"
    mapping = [
        ("Newsreader", "Newsreader-Regular.ttf", "_FONT_SERIF"),
        ("Newsreader-Medium", "Newsreader-Medium.ttf", "_FONT_SERIF_MED"),
        ("Newsreader-SemiBold", "Newsreader-SemiBold.ttf", "_FONT_SERIF_SEMI"),
        ("Newsreader-Italic", "Newsreader-Italic.ttf", "_FONT_SERIF_ITALIC"),
        ("Newsreader-MediumItalic", "Newsreader-MediumItalic.ttf", "_FONT_SERIF_MED_ITALIC"),
        ("LibreFranklin", "LibreFranklin-Regular.ttf", "_FONT_SANS"),
        ("LibreFranklin-Medium", "LibreFranklin-Medium.ttf", "_FONT_SANS_MED"),
        ("LibreFranklin-SemiBold", "LibreFranklin-SemiBold.ttf", "_FONT_SANS_SEMI"),
        ("LibreFranklin-Bold", "LibreFranklin-Bold.ttf", "_FONT_SANS_BOLD"),
    ]
    g = globals()
    registered = set()
    for face, filename, var in mapping:
        path = fonts_dir / filename
        if path.is_file():
            try:
                pdfmetrics.registerFont(TTFont(face, str(path)))
                g[var] = face
                registered.add(face)
            except Exception:
                pass
    # Enable <i>/<b> tags for Newsreader / Libre Franklin in Paragraph mini-HTML.
    if {"Newsreader", "Newsreader-Italic", "Newsreader-SemiBold", "Newsreader-MediumItalic"} <= registered:
        pdfmetrics.registerFontFamily(
            "Newsreader",
            normal="Newsreader",
            bold="Newsreader-SemiBold",
            italic="Newsreader-Italic",
            boldItalic="Newsreader-MediumItalic",
        )
    if {"LibreFranklin", "LibreFranklin-Bold"} <= registered:
        pdfmetrics.registerFontFamily(
            "LibreFranklin",
            normal="LibreFranklin",
            bold="LibreFranklin-Bold",
            italic="LibreFranklin",
            boldItalic="LibreFranklin-Bold",
        )


def _float(v: Any) -> float:
    if v is None:
        return 0.0
    if isinstance(v, Decimal):
        return float(v)
    try:
        return float(v)
    except (TypeError, ValueError):
        return 0.0


def _str(v: Any) -> str:
    if v is None:
        return "—"
    return str(v).strip() or "—"


def _xml_safe(v: Any) -> str:
    """Escape for ReportLab Paragraph mini-HTML."""
    if v is None:
        return "—"
    t = str(v).strip()
    if not t:
        return "—"
    return escape(t)


def _sell_grade(so: Dict[str, Any]) -> int:
    g = so.get("grade")
    if g is None:
        return 2
    try:
        return int(g)
    except (TypeError, ValueError):
        return 2


def _money(n: float, blank_zero: bool = False) -> str:
    if blank_zero and abs(n) < 0.5:
        return "—"
    sign = "-" if n < 0 else ""
    return f"{sign}${abs(n):,.0f}"


def _pct(n: float, decimals: int = 1, blank_zero: bool = False) -> str:
    if blank_zero and abs(n) < 0.05:
        return "—"
    return f"{n:.{decimals}f}%"


def _gain_retention_rate(net_gain_loss: float, pre_unrealized: float) -> Optional[float]:
    if abs(pre_unrealized) < 1e-9:
        return None
    return 100.0 - (net_gain_loss / pre_unrealized * 100.0)


# ---------------------------------------------------------------------------
# Custom flowables
# ---------------------------------------------------------------------------
class StackedBar(Flowable):
    """Horizontal stacked allocation bar with 1px white dividers."""

    def __init__(self, segments: List[Tuple[float, colors.Color]], width: float, height: float = 22):
        super().__init__()
        self.segments = [(w, c) for w, c in segments if w > 0]
        self._bar_width = width
        self._bar_height = height

    def wrap(self, availWidth, availHeight):
        self.width = self._bar_width
        self.height = self._bar_height
        return self.width, self.height

    def draw(self):
        self.canv.setStrokeColor(AUOUR_BORDER)
        self.canv.setLineWidth(0.75)
        self.canv.setFillColor(colors.white)
        self.canv.rect(0, 0, self.width, self.height, stroke=1, fill=1)
        total = sum(w for w, _ in self.segments) or 1.0
        x = 0.0
        for i, (w, c) in enumerate(self.segments):
            seg_w = self.width * (w / total)
            self.canv.setFillColor(c)
            self.canv.rect(x, 0, seg_w, self.height, stroke=0, fill=1)
            if i < len(self.segments) - 1 and seg_w > 1:
                self.canv.setStrokeColor(colors.white)
                self.canv.setLineWidth(1)
                self.canv.line(x + seg_w, 0, x + seg_w, self.height)
            x += seg_w
        self.canv.setStrokeColor(AUOUR_BORDER)
        self.canv.setLineWidth(0.75)
        self.canv.rect(0, 0, self.width, self.height, stroke=1, fill=0)


class AllocationLegend(Flowable):
    """Wrapping chip+label legend (sample uses ~4 items/row, natural gaps)."""

    def __init__(
        self,
        items: List[Tuple[colors.Color, str]],
        width: float,
        chip: float = 8,
        font_size: float = 8.2,
        col_gap: float = 16,
        row_gap: float = 6,
    ):
        super().__init__()
        self.items = items
        self._avail_width = width
        self.chip = chip
        self.font_size = font_size
        self.col_gap = col_gap
        self.row_gap = row_gap
        self._rows: List[List[Tuple[colors.Color, str, float]]] = []

    def wrap(self, availWidth, availHeight):
        self.width = min(self._avail_width, availWidth)
        # Measure and wrap into rows (flex-wrap style, like the sample)
        self._rows = []
        row: List[Tuple[colors.Color, str, float]] = []
        x = 0.0
        for color, label in self.items:
            text_w = pdfmetrics.stringWidth(label, _FONT_SANS, self.font_size)
            item_w = self.chip + 5 + text_w
            if row and x + item_w > self.width:
                self._rows.append(row)
                row = []
                x = 0.0
            row.append((color, label, item_w))
            x += item_w + self.col_gap
        if row:
            self._rows.append(row)
        line_h = max(self.chip, self.font_size) + 2
        self.height = len(self._rows) * line_h + max(0, len(self._rows) - 1) * self.row_gap
        return self.width, self.height

    def draw(self):
        line_h = max(self.chip, self.font_size) + 2
        y = self.height - line_h
        for row in self._rows:
            # Distribute leftover horizontal space across gaps so the row
            # spans the full content width (avoids a left-clustered look).
            content_w = sum(item_w for _, _, item_w in row)
            gaps = max(0, len(row) - 1)
            if gaps:
                gap = max(self.col_gap, (self.width - content_w) / gaps)
            else:
                gap = 0.0
            # Cap gap so short final rows don't stretch awkwardly
            if gaps and gap > 36:
                gap = self.col_gap
            x = 0.0
            for color, label, item_w in row:
                self.canv.setFillColor(color)
                self.canv.rect(x, y + 1, self.chip, self.chip, stroke=0, fill=1)
                self.canv.setFillColor(AUOUR_NAVY_MUTED)
                self.canv.setFont(_FONT_SANS, self.font_size)
                self.canv.drawString(x + self.chip + 5, y + 1, label)
                x += item_w + gap
            y -= line_h + self.row_gap


class ComparisonBars(Flowable):
    """Current (navy) vs Proposed (brass) bars scaled to the max value across all rows."""

    def __init__(
        self,
        rows: List[Tuple[str, float, float]],
        width: float,
        label_width: float = 150,
        row_gap: float = 5,
    ):
        super().__init__()
        self.rows = rows
        self._avail_width = width
        self.label_width = label_width
        self.row_gap = row_gap
        self.bar_h = 8
        self.pair_gap = 4
        self.pct_w = 40
        self.row_h = self.bar_h * 2 + self.pair_gap + self.row_gap
        self._scale = max((max(c, p) for _, c, p in rows), default=1.0) or 1.0

    def wrap(self, availWidth, availHeight):
        # Must assign self.height here — draw() relies on it; if left at 0,
        # bars render below the reserved box and overlap following content.
        self.width = min(self._avail_width, availWidth)
        self.track_w = max(40.0, self.width - self.label_width - 14 - self.pct_w)
        self.height = len(self.rows) * self.row_h
        return self.width, self.height

    def draw(self):
        y = self.height - self.row_h
        for name, cur, prop in self.rows:
            self.canv.setFillColor(AUOUR_NAVY)
            self.canv.setFont(_FONT_SANS_MED, 9)
            label_y = y + self.bar_h + self.pair_gap / 2 - 1
            self.canv.drawString(0, label_y, name[:28])

            track_x = self.label_width + 12

            def draw_bar(value: float, color: colors.Color, bar_y: float, label: str):
                self.canv.setFillColor(AUOUR_TRACK)
                self.canv.rect(track_x, bar_y, self.track_w, self.bar_h, stroke=0, fill=1)
                fill_w = self.track_w * (value / self._scale) if self._scale else 0
                if fill_w > 0:
                    self.canv.setFillColor(color)
                    self.canv.rect(track_x, bar_y, fill_w, self.bar_h, stroke=0, fill=1)
                self.canv.setFillColor(AUOUR_NAVY_MUTED)
                self.canv.setFont(_FONT_SANS, 8.2)
                self.canv.drawRightString(
                    track_x + self.track_w + self.pct_w, bar_y + 0.5, label
                )

            draw_bar(cur, AUOUR_NAVY, y + self.bar_h + self.pair_gap, _pct(cur, 1, blank_zero=True))
            draw_bar(prop, AUOUR_BRASS, y, _pct(prop, 1, blank_zero=True))

            # Row rule between pairs only (not under the last row — avoids
            # colliding with the caption that follows the chart).
            rule_y = y - self.row_gap / 2
            if rule_y > self.row_gap:
                self.canv.setStrokeColor(AUOUR_ROW_RULE)
                self.canv.setLineWidth(0.5)
                self.canv.line(0, rule_y, self.width, rule_y)
            y -= self.row_h


class ColorChip(Flowable):
    def __init__(self, color: colors.Color, size: float = 11):
        super().__init__()
        self.color = color
        self.size = size

    def wrap(self, availWidth, availHeight):
        self.width = self.size
        self.height = self.size
        return self.width, self.height

    def draw(self):
        self.canv.setFillColor(self.color)
        self.canv.rect(0, 0, self.size, self.size, stroke=0, fill=1)


class SectionHeader(Flowable):
    """Brass section number + Newsreader title with bottom rule.

    Sized to match sample PDF (~11pt number, ~18pt title), not the larger HTML prototype.
    """

    def __init__(self, number: str, title: str, width: float):
        super().__init__()
        self.number = number
        self.title = title
        self.width = width
        self.height = 28

    def wrap(self, availWidth, availHeight):
        return self.width, self.height

    def draw(self):
        self.canv.setFillColor(AUOUR_BRASS)
        self.canv.setFont(_FONT_SERIF_SEMI, 11)
        self.canv.drawString(0, 10, self.number)
        num_w = self.canv.stringWidth(self.number, _FONT_SERIF_SEMI, 11)
        self.canv.setFillColor(AUOUR_NAVY)
        self.canv.setFont(_FONT_SERIF_MED, 18)
        self.canv.drawString(num_w + 12, 8, self.title)
        self.canv.setStrokeColor(AUOUR_BORDER_STRONG)
        self.canv.setLineWidth(0.75)
        self.canv.line(0, 0, self.width, 0)


class StatCard(Flowable):
    """Fixed-height impact summary card (equal boxes, sample = 108pt tall)."""

    def __init__(
        self,
        label: str,
        value: str,
        note: str,
        width: float,
        height: float = STAT_CARD_H,
        tinted: bool = False,
        green: bool = False,
    ):
        super().__init__()
        self.label = label
        self.value = value
        self.note = note
        self.width = width
        self.height = height
        self.tinted = tinted
        self.green = green

    def wrap(self, availWidth, availHeight):
        return self.width, self.height

    def draw(self):
        pad = STAT_CARD_PAD
        # Background + border (tinted card still gets a border in the sample)
        self.canv.setStrokeColor(AUOUR_BORDER)
        self.canv.setLineWidth(0.75)
        if self.tinted:
            self.canv.setFillColor(AUOUR_STAT_TINT)
            self.canv.rect(0, 0, self.width, self.height, stroke=1, fill=1)
        else:
            self.canv.setFillColor(colors.white)
            self.canv.rect(0, 0, self.width, self.height, stroke=1, fill=0)

        # Label
        self.canv.setFillColor(AUOUR_GRAY)
        self.canv.setFont(_FONT_SANS, 7)
        self.canv.drawString(pad, self.height - pad - 7, self.label.upper())

        # Value
        self.canv.setFillColor(AUOUR_GREEN if self.green else AUOUR_NAVY)
        self.canv.setFont(_FONT_SERIF_SEMI if self.green else _FONT_SERIF, 22)
        self.canv.drawString(pad, self.height - pad - 36, self.value)

        # Note — wrap manually to fixed card width
        self.canv.setFillColor(AUOUR_GRAY_MID)
        self.canv.setFont(_FONT_SANS, 8)
        max_w = self.width - 2 * pad
        words = self.note.split()
        lines: List[str] = []
        cur = ""
        for word in words:
            trial = f"{cur} {word}".strip()
            if self.canv.stringWidth(trial, _FONT_SANS, 8) <= max_w:
                cur = trial
            else:
                if cur:
                    lines.append(cur)
                cur = word
        if cur:
            lines.append(cur)
        # Anchor notes near bottom of card
        line_h = 11
        y = pad + line_h * (len(lines) - 1)
        for line in lines:
            self.canv.drawString(pad, y, line)
            y -= line_h


class TradeSubhead(Flowable):
    """Colored subheading with trailing rule (Sells / Buys)."""

    def __init__(self, text: str, color: colors.Color, width: float):
        super().__init__()
        self.text = text
        self.color = color
        self.width = width
        self.height = 16

    def wrap(self, availWidth, availHeight):
        return self.width, self.height

    def draw(self):
        self.canv.setFillColor(self.color)
        self.canv.setFont(_FONT_SERIF, 12)
        self.canv.drawString(0, 3, self.text)
        tw = self.canv.stringWidth(self.text, _FONT_SERIF, 12)
        self.canv.setStrokeColor(AUOUR_BORDER)
        self.canv.setLineWidth(0.75)
        self.canv.line(tw + 8, 8, self.width, 8)


# ---------------------------------------------------------------------------
# Style helpers
# ---------------------------------------------------------------------------
def _build_styles() -> Dict[str, ParagraphStyle]:
    """Typography calibrated to Transition Report Sample 7.9.26.pdf measurements."""
    _register_fonts()
    base = getSampleStyleSheet()
    return {
        "body": ParagraphStyle(
            "Body",
            parent=base["Normal"],
            fontName=_FONT_SANS,
            fontSize=9.8,
            leading=15.7,
            textColor=AUOUR_NAVY,
            spaceAfter=14,
        ),
        "body_muted": ParagraphStyle(
            "BodyMuted",
            parent=base["Normal"],
            fontName=_FONT_SANS,
            fontSize=9.8,
            leading=15.7,
            textColor=AUOUR_NAVY_MUTED,
            spaceAfter=14,
        ),
        "caption": ParagraphStyle(
            "Caption",
            parent=base["Normal"],
            fontName=_FONT_SANS,
            fontSize=8.2,
            leading=12,
            textColor=AUOUR_GRAY,
            spaceBefore=8,
        ),
        "th": ParagraphStyle(
            "TableHeader",
            parent=base["Normal"],
            fontName=_FONT_SANS_SEMI,
            fontSize=7.5,
            leading=10,
            textColor=AUOUR_GRAY_MID,
        ),
        "td": ParagraphStyle(
            "TableCell",
            parent=base["Normal"],
            fontName=_FONT_SANS,
            fontSize=9.4,
            leading=12.5,
            textColor=AUOUR_NAVY_MUTED,
        ),
        "td_strong": ParagraphStyle(
            "TableCellStrong",
            parent=base["Normal"],
            fontName=_FONT_SANS_SEMI,
            fontSize=9.4,
            leading=12.5,
            textColor=AUOUR_NAVY,
        ),
        "td_right": ParagraphStyle(
            "TableCellRight",
            parent=base["Normal"],
            fontName=_FONT_SANS,
            fontSize=9.4,
            leading=12.5,
            textColor=AUOUR_NAVY,
            alignment=TA_RIGHT,
        ),
        "td_right_muted": ParagraphStyle(
            "TableCellRightMuted",
            parent=base["Normal"],
            fontName=_FONT_SANS,
            fontSize=9.4,
            leading=12.5,
            textColor=AUOUR_GRAY,
            alignment=TA_RIGHT,
        ),
        "td_green": ParagraphStyle(
            "TableCellGreen",
            parent=base["Normal"],
            fontName=_FONT_SANS,
            fontSize=9.4,
            leading=12.5,
            textColor=AUOUR_GREEN,
            alignment=TA_RIGHT,
        ),
        "td_red": ParagraphStyle(
            "TableCellRed",
            parent=base["Normal"],
            fontName=_FONT_SANS,
            fontSize=9.4,
            leading=12.5,
            textColor=AUOUR_RED,
            alignment=TA_RIGHT,
        ),
        "td_gray": ParagraphStyle(
            "TableCellGray",
            parent=base["Normal"],
            fontName=_FONT_SANS,
            fontSize=9.4,
            leading=12.5,
            textColor=colors.HexColor("#9AA3B0"),
            alignment=TA_RIGHT,
        ),
        "subtotal": ParagraphStyle(
            "Subtotal",
            parent=base["Normal"],
            fontName=_FONT_SANS_SEMI,
            fontSize=9.4,
            leading=12.5,
            textColor=AUOUR_NAVY,
        ),
        "subtotal_right": ParagraphStyle(
            "SubtotalRight",
            parent=base["Normal"],
            fontName=_FONT_SANS_SEMI,
            fontSize=9.4,
            leading=12.5,
            textColor=AUOUR_NAVY,
            alignment=TA_RIGHT,
        ),
        "note_title": ParagraphStyle(
            "NoteTitle",
            parent=base["Normal"],
            fontName=_FONT_SERIF,
            fontSize=12,
            leading=16,
            textColor=AUOUR_NAVY,
            spaceAfter=3,
            spaceBefore=2,
        ),
        "note_body": ParagraphStyle(
            "NoteBody",
            parent=base["Normal"],
            fontName=_FONT_SANS,
            fontSize=9.8,
            leading=15.7,
            textColor=AUOUR_NAVY,
            spaceAfter=12,
        ),
        "holdings_label": ParagraphStyle(
            "HoldingsLabel",
            parent=base["Normal"],
            fontName=_FONT_SERIF_ITALIC,
            fontSize=11,
            leading=14,
            textColor=AUOUR_NAVY_SOFT,
            spaceBefore=14,
            spaceAfter=4,
        ),
        "eyebrow": ParagraphStyle(
            "Eyebrow",
            parent=base["Normal"],
            fontName=_FONT_SERIF,
            fontSize=9.8,
            leading=12,
            textColor=AUOUR_BRASS,
            spaceBefore=0,
            spaceAfter=4,
        ),
        "cover_title": ParagraphStyle(
            "CoverTitle",
            parent=base["Normal"],
            fontName=_FONT_SERIF_MED,
            fontSize=40.5,
            leading=42,
            textColor=AUOUR_NAVY,
            spaceBefore=0,
            spaceAfter=0,
        ),
        "meta_label": ParagraphStyle(
            "MetaLabel",
            parent=base["Normal"],
            fontName=_FONT_SANS,
            fontSize=7.1,
            leading=9,
            textColor=AUOUR_GRAY,
            spaceBefore=0,
            spaceAfter=3,
        ),
        "meta_value": ParagraphStyle(
            "MetaValue",
            parent=base["Normal"],
            fontName=_FONT_SERIF,
            fontSize=12,
            leading=15,
            textColor=AUOUR_NAVY,
            spaceBefore=0,
            spaceAfter=0,
        ),
        "wordmark": ParagraphStyle(
            "Wordmark",
            parent=base["Normal"],
            fontName=_FONT_SERIF_MED,
            fontSize=14.2,
            leading=16,
            textColor=AUOUR_NAVY,
            spaceBefore=0,
            spaceAfter=0,
        ),
        "wordmark_sub": ParagraphStyle(
            "WordmarkSub",
            parent=base["Normal"],
            fontName=_FONT_SANS,
            fontSize=7.5,
            leading=9,
            textColor=AUOUR_GRAY,
            spaceBefore=1,
            spaceAfter=0,
        ),
        "confidential": ParagraphStyle(
            "Confidential",
            parent=base["Normal"],
            fontName=_FONT_SANS_SEMI,
            fontSize=6.8,
            leading=9,
            textColor=AUOUR_BRASS,
            alignment=TA_RIGHT,
            spaceBefore=0,
            spaceAfter=0,
        ),
        "legend": ParagraphStyle(
            "Legend",
            parent=base["Normal"],
            fontName=_FONT_SANS,
            fontSize=8.2,
            leading=11,
            textColor=AUOUR_NAVY_MUTED,
        ),
        "callout": ParagraphStyle(
            "Callout",
            parent=base["Normal"],
            fontName=_FONT_SANS,
            fontSize=9,
            leading=13.5,
            textColor=AUOUR_CALLOUT_TEXT,
        ),
        "disclosure_label": ParagraphStyle(
            "DisclosureLabel",
            parent=base["Normal"],
            fontName=_FONT_SANS_SEMI,
            fontSize=7.1,
            leading=10,
            textColor=AUOUR_GRAY,
            spaceAfter=5,
        ),
        "disclosure_body": ParagraphStyle(
            "DisclosureBody",
            parent=base["Normal"],
            fontName=_FONT_SANS,
            fontSize=7.5,
            leading=11.5,
            textColor=AUOUR_GRAY,
        ),
        "alloc_label": ParagraphStyle(
            "AllocLabel",
            parent=base["Normal"],
            fontName=_FONT_SANS,
            fontSize=7.1,
            leading=9,
            textColor=AUOUR_GRAY,
            spaceAfter=5,
        ),
    }


def _p(text: str, style: ParagraphStyle) -> Paragraph:
    return Paragraph(_xml_safe(text), style)


def _p_html(html: str, style: ParagraphStyle) -> Paragraph:
    """Paragraph with trusted mini-HTML (already escaped user bits)."""
    return Paragraph(html, style)


def _table_header_row(labels: List[str], styles: Dict[str, ParagraphStyle], aligns: Optional[List[str]] = None) -> List[Paragraph]:
    aligns = aligns or ["LEFT"] * len(labels)
    out = []
    for label, align in zip(labels, aligns):
        st = ParagraphStyle(
            f"th_{label}_{align}",
            parent=styles["th"],
            alignment=TA_RIGHT if align == "RIGHT" else TA_LEFT,
        )
        out.append(Paragraph(label.upper(), st))
    return out


def _brand_table_style(n_rows: int, subtotal_rows: Optional[List[int]] = None) -> TableStyle:
    cmds = [
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, 0), 0),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 6),
        ("TOPPADDING", (0, 1), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 1), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("LINEBELOW", (0, 0), (-1, 0), 1.25, AUOUR_NAVY),
        ("LINEBELOW", (0, 1), (-1, -2), 0.5, AUOUR_ROW_RULE),
    ]
    for idx in subtotal_rows or []:
        cmds.append(("BACKGROUND", (0, idx), (-1, idx), AUOUR_SUBTOTAL_BG))
    return TableStyle(cmds)


def _split_paragraphs(additional_text: Optional[str]) -> List[str]:
    """Split optional narrative into paragraphs on blank lines."""
    if not additional_text:
        return []
    normalized = str(additional_text).replace("\r\n", "\n").replace("\r", "\n")
    return [p.strip() for p in normalized.split("\n\n") if p.strip()]


def _asset_class_sort_key(ac: str, order_index: Dict[str, int]):
    ac_norm = (ac or "").strip()
    if ac_norm in {"Side Pocket", "Forced Sale"}:
        return (2, 9999, ac_norm)
    if ac in order_index:
        return (0, order_index[ac], ac)
    return (1, 9999, ac_norm)


def _build_holdings_table_rows(
    holdings: List[Dict[str, Any]],
    side: str,
    portfolio_total: float,
    asset_class_order: List[str],
    styles: Dict[str, ParagraphStyle],
) -> Tuple[List[List[Any]], List[int]]:
    grouped: Dict[str, List[Dict[str, Any]]] = defaultdict(list)
    for r in holdings:
        grouped[_str(r.get("asset_class"))].append(r)
    order_index = {name: idx for idx, name in enumerate(asset_class_order)}

    rows: List[List[Any]] = [
        _table_header_row(
            ["Ticker", "Asset Class", "Value ($)", "Unrealized ($)", "% Total"],
            styles,
            ["LEFT", "LEFT", "RIGHT", "RIGHT", "RIGHT"],
        )
    ]
    subtotal_idxs: List[int] = []

    for asset_class in sorted(grouped.keys(), key=lambda ac: _asset_class_sort_key(ac, order_index)):
        items = grouped[asset_class]
        for h in items:
            ticker = _str(h.get("ticker")) if side == "current" else _str(h.get("ticker") or h.get("model_ticker"))
            val = _float(h.get("value"))
            unreal = _float(h.get("unrealized_gain_loss"))
            pct = (val / portfolio_total * 100) if portfolio_total else 0.0
            if unreal > 0:
                u_style = styles["td_green"]
                u_txt = f"{unreal:,.0f}"
            elif unreal < 0:
                u_style = styles["td_red"]
                u_txt = f"{unreal:,.0f}"
            else:
                u_style = styles["td_gray"]
                u_txt = "—"
            rows.append([
                _p(ticker, styles["td_strong"]),
                _p(asset_class, styles["td"]),
                Paragraph(_xml_safe(f"{val:,.0f}" if abs(val) >= 0.5 else "—"), styles["td_right"]),
                Paragraph(_xml_safe(u_txt), u_style),
                Paragraph(_xml_safe(_pct(pct, 1, blank_zero=True)), styles["td_right_muted"]),
            ])
        ac_val = sum(_float(h.get("value")) for h in items)
        ac_unreal = sum(_float(h.get("unrealized_gain_loss")) for h in items)
        ac_pct = (ac_val / portfolio_total * 100) if portfolio_total else 0.0
        rows.append([
            Paragraph("", styles["subtotal"]),
            Paragraph(_xml_safe(f"{asset_class} subtotal"), styles["subtotal"]),
            Paragraph(_xml_safe(f"{ac_val:,.0f}"), styles["subtotal_right"]),
            Paragraph(
                _xml_safe(f"{ac_unreal:,.0f}" if abs(ac_unreal) >= 0.5 else "—"),
                styles["subtotal_right"],
            ),
            Paragraph(_xml_safe(_pct(ac_pct, 1, blank_zero=True)), styles["subtotal_right"]),
        ])
        subtotal_idxs.append(len(rows) - 1)

    return rows, subtotal_idxs


def build_transition_report_pdf(
    prospect_name: str,
    strategy_name: str,
    report_date: Optional[date] = None,
    total_value: float = 0.0,
    total_gains: float = 0.0,
    total_losses: float = 0.0,
    net_gain_loss: float = 0.0,
    pre_unrealized_gain_loss: float = 0.0,
    post_unrealized_gain_loss: float = 0.0,
    cash_residual: float = 0.0,
    additional_text: Optional[str] = None,
    pre_holdings: Optional[List[Dict[str, Any]]] = None,
    post_holdings: Optional[List[Dict[str, Any]]] = None,
    sell_orders: Optional[List[Dict[str, Any]]] = None,
    buy_orders: Optional[List[Dict[str, Any]]] = None,
    equivalent_usage: Optional[List[Dict[str, Any]]] = None,
    asset_class_order: Optional[List[str]] = None,
    target_positions: Optional[List[Dict[str, Any]]] = None,
) -> bytes:
    """
    Build a portrait Letter PDF transition report matching the Auour design template.
    Signature is unchanged for callers in prospects.py.
    """
    _register_fonts()
    report_date = report_date or date.today()
    pre_holdings = pre_holdings or []
    post_holdings = post_holdings or []
    sell_orders = sell_orders or []
    buy_orders = buy_orders or []
    equivalent_usage_list = list(equivalent_usage or [])
    asset_class_order = list(asset_class_order or [])
    target_positions = list(target_positions or [])

    styles = _build_styles()
    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=letter,
        leftMargin=PAGE_MARGIN,
        rightMargin=PAGE_MARGIN,
        topMargin=PAGE_MARGIN,
        bottomMargin=0.7 * inch,
    )
    story: List[Any] = []
    w = CONTENT_WIDTH_PT

    # =====================================================================
    # COVER + 01 on first page (matches sample PDF pagination)
    # =====================================================================
    header = Table(
        [[
            [
                Paragraph("Auour Investments", styles["wordmark"]),
                Paragraph("BOSTON, MASSACHUSETTS · EST. 2013", styles["wordmark_sub"]),
            ],
            Paragraph("C O N F I D E N T I A L", styles["confidential"]),
        ]],
        colWidths=[w * 0.72, w * 0.28],
    )
    header.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
    ]))
    story.append(header)
    # Sample gaps (pt): wordmark→eyebrow ≈55, title→meta ≈52, meta→01 ≈98, 01→cards ≈59
    story.append(Spacer(1, 44))

    # Strategy eyebrow — append "STRATEGY" when not already present (sample shows full label)
    eyebrow = strategy_name.strip()
    if "strategy" not in eyebrow.lower():
        eyebrow = f"{eyebrow} Strategy"
    story.append(Paragraph(_xml_safe(eyebrow).upper(), styles["eyebrow"]))

    cover_title_style = ParagraphStyle(
        "CoverTitleHtml",
        parent=styles["cover_title"],
        fontName=_FONT_SERIF_MED if _FONT_SERIF_MED != "Helvetica" else "Helvetica",
    )
    if _FONT_SERIF_ITALIC != "Helvetica-Oblique":
        story.append(Paragraph(
            f'Transition <font name="{_FONT_SERIF_ITALIC}">Report</font>',
            cover_title_style,
        ))
    else:
        story.append(Paragraph("Transition <i>Report</i>", cover_title_style))
    # Sample: title box bottom ~187 → meta ~239 (≈52pt including rule)
    story.append(Spacer(1, 40))
    story.append(HRFlowable(width="100%", thickness=0.75, color=AUOUR_BORDER_STRONG, spaceBefore=0, spaceAfter=16))

    meta = Table(
        [[
            [
                Paragraph("PROSPECT", styles["meta_label"]),
                Paragraph(_xml_safe(prospect_name), styles["meta_value"]),
            ],
            [
                Paragraph("STRATEGY", styles["meta_label"]),
                Paragraph(_xml_safe(strategy_name), styles["meta_value"]),
            ],
            [
                Paragraph("REPORT DATE", styles["meta_label"]),
                Paragraph(_xml_safe(report_date.strftime("%B %d, %Y")), styles["meta_value"]),
            ],
        ]],
        colWidths=[w / 3.0, w / 3.0, w / 3.0],
    )
    meta.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (1, -1), 12),
        ("RIGHTPADDING", (2, 0), (2, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
    ]))
    story.append(meta)
    # Sample: meta block ends ~y275, section header ~y333
    story.append(Spacer(1, 44))

    # ----- 01 Portfolio Impact Summary (continues on page 1) -----
    story.append(SectionHeader("01", "Portfolio Impact Summary", w))
    story.append(Spacer(1, 28))

    retention = _gain_retention_rate(net_gain_loss, pre_unrealized_gain_loss)
    retention_label = f"{retention:.1f}%" if retention is not None else "—"
    retention_caption = (
        f"Share of current unrealized gain deferred "
        f"(100% − {_money(net_gain_loss)} ÷ {_money(pre_unrealized_gain_loss)})"
        if retention is not None
        else "Unavailable when current unrealized is zero"
    )

    card_w = (w - 2 * STAT_CARD_GAP) / 3.0
    cards = Table(
        [[
            StatCard(
                "Net Realized Gain / Loss",
                _money(net_gain_loss),
                "Tax realization from proposed trades",
                width=card_w,
            ),
            StatCard(
                "Unrealized — Current",
                _money(pre_unrealized_gain_loss),
                "Unrealized amount before transition",
                width=card_w,
            ),
            StatCard(
                "Gain Retention Rate",
                retention_label,
                retention_caption,
                width=card_w,
                tinted=True,
                green=True,
            ),
        ]],
        colWidths=[card_w, card_w, card_w],
        hAlign="LEFT",
    )
    cards.setStyle(TableStyle([
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (1, -1), STAT_CARD_GAP),
        ("RIGHTPADDING", (2, 0), (2, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    story.append(cards)
    # Sample: card top ~381 → body ~512; card height 108 → ~23pt after cards
    story.append(Spacer(1, 22))

    for p in _split_paragraphs(additional_text):
        story.append(Paragraph(_xml_safe(p), styles["body"]))

    story.append(PageBreak())

    # =====================================================================
    # 02 — Target Model Portfolio
    # =====================================================================
    story.append(SectionHeader("02", "Target Model Portfolio", w))
    story.append(Spacer(1, 18))

    if target_positions:
        # Aggregate by asset class for stacked bar (sum of target allocations)
        by_ac_target: Dict[str, float] = defaultdict(float)
        for p in target_positions:
            by_ac_target[_str(p.get("asset_class"))] += _float(p.get("target_allocation"))

        # Order segments by descending weight
        ac_segments = sorted(by_ac_target.items(), key=lambda kv: -kv[1])
        bar_segs = [
            (pct, CHART_PALETTE[i % len(CHART_PALETTE)])
            for i, (_, pct) in enumerate(ac_segments)
        ]
        story.append(Paragraph("TARGET ALLOCATION", styles["alloc_label"]))
        story.append(StackedBar(bar_segs, w, height=22))
        story.append(Spacer(1, 10))

        legend_items = [
            (CHART_PALETTE[i % len(CHART_PALETTE)], f"{ac} {_pct(pct, 2)}")
            for i, (ac, pct) in enumerate(ac_segments)
        ]
        story.append(AllocationLegend(legend_items, w, chip=8, font_size=8.2, col_gap=18, row_gap=6))
        story.append(Spacer(1, 18))

        # Detail table (per ticker, no asset-class subtotals — matches design)
        by_ac: Dict[str, List[Dict[str, Any]]] = defaultdict(list)
        for p in target_positions:
            by_ac[_str(p.get("asset_class"))].append(p)
        ac_order = sorted(
            by_ac.keys(),
            key=lambda ac: -max(_float(x.get("target_allocation")) for x in by_ac[ac]),
        )
        target_rows: List[List[Any]] = [
            _table_header_row(
                ["Model Ticker", "Asset Class", "Target %", "Drift %"],
                styles,
                ["LEFT", "LEFT", "RIGHT", "RIGHT"],
            )
        ]
        for ac in ac_order:
            items = sorted(by_ac[ac], key=lambda x: -_float(x.get("target_allocation")))
            for p in items:
                target_rows.append([
                    _p(_str(p.get("model_ticker")), styles["td_strong"]),
                    _p(ac, styles["td"]),
                    Paragraph(_xml_safe(_pct(_float(p.get("target_allocation")), 2)), styles["td_right"]),
                    Paragraph(
                        _xml_safe(f"±{_float(p.get('drift_percentage')):.2f}%"),
                        styles["td_right_muted"],
                    ),
                ])
        target_rows.append([
            Paragraph("Total", styles["subtotal"]),
            Paragraph("", styles["subtotal"]),
            Paragraph("100.00%", styles["subtotal_right"]),
            Paragraph("", styles["subtotal_right"]),
        ])
        target_table = Table(
            target_rows,
            colWidths=[w * 0.22, w * 0.38, w * 0.20, w * 0.20],
            repeatRows=1,
        )
        ts = _brand_table_style(len(target_rows))
        ts.add("BACKGROUND", (0, -1), (-1, -1), AUOUR_SUBTOTAL_BG)
        target_table.setStyle(ts)
        story.append(target_table)
    else:
        story.append(Paragraph("Target portfolio not available for this result.", styles["body_muted"]))

    story.append(PageBreak())

    # =====================================================================
    # 03 — Current vs. Proposed by Asset Class
    # =====================================================================
    story.append(SectionHeader("03", "Current vs. Proposed by Asset Class", w))
    story.append(Spacer(1, 12))

    legend_cur = Table(
        [[ColorChip(AUOUR_NAVY, 9), Paragraph("Current", styles["legend"]),
          ColorChip(AUOUR_BRASS, 9), Paragraph("Proposed", styles["legend"])]],
        colWidths=[14, 58, 14, 70],
    )
    legend_cur.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
    ]))
    story.append(legend_cur)
    story.append(Spacer(1, 10))

    legacy_total_val = sum(_float(h.get("value")) for h in pre_holdings) or 0.0
    proposed_total_val = sum(_float(h.get("value")) for h in post_holdings) or 0.0

    current_by_ac: Dict[str, float] = defaultdict(float)
    proposed_by_ac: Dict[str, float] = defaultdict(float)
    for h in pre_holdings:
        current_by_ac[_str(h.get("asset_class"))] += _float(h.get("value"))
    for h in post_holdings:
        proposed_by_ac[_str(h.get("asset_class"))] += _float(h.get("value"))

    order_index = {name: i for i, name in enumerate(asset_class_order)}
    all_acs = sorted(
        set(list(current_by_ac.keys()) + list(proposed_by_ac.keys())),
        key=lambda ac: _asset_class_sort_key(ac, order_index),
    )
    # Exclude Side Pocket from bar chart (design shows Forced Sale; Side Pocket rolls into narrative)
    compare_rows: List[Tuple[str, float, float]] = []
    for ac in all_acs:
        if ac == "Side Pocket":
            continue
        cur_pct = (current_by_ac.get(ac, 0.0) / legacy_total_val * 100) if legacy_total_val else 0.0
        prop_pct = (proposed_by_ac.get(ac, 0.0) / proposed_total_val * 100) if proposed_total_val else 0.0
        compare_rows.append((ac, cur_pct, prop_pct))

    if compare_rows:
        story.append(ComparisonBars(compare_rows, w, label_width=150))
        story.append(Spacer(1, 16))

    forced_pct = (
        (current_by_ac.get("Forced Sale", 0.0) + current_by_ac.get("Side Pocket", 0.0))
        / legacy_total_val * 100
        if legacy_total_val
        else 0.0
    )
    if forced_pct > 0.05:
        story.append(Paragraph(
            _xml_safe(
                f"Forced Sale and individual securities in the current portfolio "
                f"({forced_pct:.1f}%) are liquidated and redeployed across the proposed allocation."
            ),
            styles["caption"],
        ))

    story.append(PageBreak())

    # =====================================================================
    # 03 (cont.) — Holdings Detail
    # =====================================================================
    story.append(SectionHeader("03", "Holdings Detail", w))
    story.append(Spacer(1, 8))

    story.append(
        _p_html(
            f'Current portfolio <font name="{_FONT_SANS}" size="11" color="#8A93A0">'
            f"(includes side pocket)</font>",
            styles["holdings_label"],
        )
    )
    cur_rows, cur_subs = _build_holdings_table_rows(
        pre_holdings, "current", legacy_total_val or 1.0, asset_class_order, styles
    )
    cur_table = Table(
        cur_rows,
        colWidths=[w * 0.16, w * 0.30, w * 0.18, w * 0.20, w * 0.16],
        repeatRows=1,
    )
    cur_table.setStyle(_brand_table_style(len(cur_rows), cur_subs))
    story.append(cur_table)

    story.append(Paragraph("Proposed portfolio", styles["holdings_label"]))
    prop_rows, prop_subs = _build_holdings_table_rows(
        post_holdings, "proposed", proposed_total_val or 1.0, asset_class_order, styles
    )
    prop_table = Table(
        prop_rows,
        colWidths=[w * 0.16, w * 0.30, w * 0.18, w * 0.20, w * 0.16],
        repeatRows=1,
    )
    prop_table.setStyle(_brand_table_style(len(prop_rows), prop_subs))
    story.append(prop_table)
    story.append(Paragraph(
        "Totals are rounded to whole dollars; small rounding differences may occur.",
        styles["caption"],
    ))

    story.append(PageBreak())

    # =====================================================================
    # 04 — Things to Note
    # =====================================================================
    story.append(SectionHeader("04", "Things to Note", w))
    story.append(Spacer(1, 18))
    for title, body in THINGS_TO_NOTE:
        story.append(Paragraph(_xml_safe(title), styles["note_title"]))
        story.append(Paragraph(_xml_safe(body), styles["note_body"]))

    story.append(PageBreak())

    # =====================================================================
    # 05 — Trade Order Execution List
    # =====================================================================
    story.append(SectionHeader("05", "Trade Order Execution List", w))
    story.append(Spacer(1, 18))

    def sell_reasoning(grade: int) -> str:
        if grade == 0:
            return "Liquidated Grade 0 (Model) asset"
        if grade == 1:
            return "Liquidated Grade 1 equivalent"
        return "Liquidated Grade 2 asset"

    story.append(TradeSubhead("Sells", AUOUR_RED, w))
    story.append(Spacer(1, 4))
    sell_rows: List[List[Any]] = [
        _table_header_row(["Ticker", "Amount ($)", "Reasoning"], styles, ["LEFT", "RIGHT", "LEFT"])
    ]
    for so in sell_orders:
        sell_rows.append([
            _p(_str(so.get("ticker")), styles["td_strong"]),
            Paragraph(_xml_safe(f"{_float(so.get('value')):,.0f}"), styles["td_right"]),
            _p(sell_reasoning(_sell_grade(so)), styles["td"]),
        ])
    if len(sell_rows) == 1:
        sell_rows.append([
            _p("—", styles["td_strong"]),
            Paragraph("—", styles["td_right"]),
            _p("No sells", styles["td"]),
        ])
    sells_table = Table(sell_rows, colWidths=[w * 0.18, w * 0.22, w * 0.60], repeatRows=1)
    sells_table.setStyle(_brand_table_style(len(sell_rows)))
    story.append(sells_table)
    story.append(Spacer(1, 22))

    story.append(TradeSubhead("Buys", AUOUR_GREEN, w))
    story.append(Spacer(1, 4))
    buy_rows: List[List[Any]] = [
        _table_header_row(["Ticker", "Amount ($)", "Reasoning"], styles, ["LEFT", "RIGHT", "LEFT"])
    ]
    for bo in buy_orders:
        buy_rows.append([
            _p(_str(bo.get("model_ticker")), styles["td_strong"]),
            Paragraph(_xml_safe(f"{_float(bo.get('value')):,.0f}"), styles["td_right"]),
            _p(f"Rebalance to {_str(bo.get('asset_class'))}", styles["td"]),
        ])
    if len(buy_rows) == 1:
        buy_rows.append([
            _p("—", styles["td_strong"]),
            Paragraph("—", styles["td_right"]),
            _p("No buys", styles["td"]),
        ])
    buys_table = Table(buy_rows, colWidths=[w * 0.18, w * 0.22, w * 0.60], repeatRows=1)
    buys_table.setStyle(_brand_table_style(len(buy_rows)))
    story.append(buys_table)

    # =====================================================================
    # 06 — Product Equivalent Mappings
    # =====================================================================
    def _equiv_source(row: Dict[str, Any]) -> str:
        if row.get("mapping_source"):
            return str(row["mapping_source"])
        if row.get("in_product_equivalents"):
            return "ge_alt"
        if _str(row.get("legacy_ticker")).upper().strip() == "CASH":
            return "cash"
        return "not_in_ge_alt"

    source_labels = {
        "manual": "Set on proposal (manual)",
        "not_in_ge_alt": "Not in alt file",
        "ge_alt": "Product equivalents file",
        "cash": "Cash",
    }
    proposal_only = [r for r in equivalent_usage_list if _equiv_source(r) in ("manual", "not_in_ge_alt")]
    # Prefer showing action-required rows; if none, show ge_alt mappings
    mapping_rows_src = proposal_only or [
        r for r in equivalent_usage_list if _equiv_source(r) == "ge_alt"
    ]

    if equivalent_usage_list:
        # Design continues mappings after trades when space allows (no forced page break).
        story.append(Spacer(1, 36))
        story.append(SectionHeader("06", "Product Equivalent Mappings", w))
        story.append(Spacer(1, 18))

        if proposal_only:
            callout_html = (
                f'<font color="#A9773F"><b>Action required.</b></font> '
                f"{len(proposal_only)} mapping(s) used in this proposal are not in the "
                f"strategy product equivalents file. Add these pairs in "
                f"<b>Admin → Product Equivalents</b> or confirm the manual mapping was intentional."
            )
            callout = Table(
                [[Paragraph(callout_html, styles["callout"])]],
                colWidths=[w],
            )
            callout.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), AUOUR_CALLOUT_BG),
                ("BOX", (0, 0), (-1, -1), 1, colors.Color(169 / 255, 119 / 255, 63 / 255, alpha=0.4)),
                ("LINEBEFORE", (0, 0), (0, 0), 3, AUOUR_BRASS),
                ("LEFTPADDING", (0, 0), (-1, -1), 14),
                ("RIGHTPADDING", (0, 0), (-1, -1), 14),
                ("TOPPADDING", (0, 0), (-1, -1), 12),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 12),
            ]))
            story.append(callout)
            story.append(Spacer(1, 16))

        map_rows: List[List[Any]] = [
            _table_header_row(
                ["Legacy", "Model", "Grade", "How Mapped"],
                styles,
                ["LEFT", "LEFT", "LEFT", "LEFT"],
            )
        ]
        for row in mapping_rows_src:
            src = _equiv_source(row)
            map_rows.append([
                _p(_str(row.get("legacy_ticker")), styles["td_strong"]),
                _p(_str(row.get("model_ticker")), styles["td_strong"]),
                _p(_str(row.get("grade")), styles["td"]),
                _p(source_labels.get(src, src), styles["td"]),
            ])
        map_table = Table(
            map_rows,
            colWidths=[w * 0.18, w * 0.18, w * 0.12, w * 0.52],
            repeatRows=1,
        )
        map_table.setStyle(_brand_table_style(len(map_rows)))
        story.append(map_table)

    # =====================================================================
    # Additional Disclosures (always last)
    # =====================================================================
    story.append(Spacer(1, 28))
    story.append(HRFlowable(width="100%", thickness=1, color=AUOUR_BORDER, spaceBefore=0, spaceAfter=12))
    story.append(Paragraph("ADDITIONAL DISCLOSURES", styles["disclosure_label"]))
    story.append(Paragraph(_xml_safe(ADDITIONAL_DISCLOSURES), styles["disclosure_body"]))

    # ----- Footer on every page -----
    def add_footer(canvas, _doc):
        canvas.saveState()
        canvas.setStrokeColor(AUOUR_BORDER)
        canvas.setLineWidth(0.6)
        # Sample footer text sits near y≈30pt from bottom (762 on 792 page → ~30pt)
        y = 30
        canvas.line(PAGE_MARGIN, y + 12, letter[0] - PAGE_MARGIN, y + 12)
        canvas.setFillColor(AUOUR_GRAY)
        canvas.setFont(_FONT_SANS, 7.1)
        canvas.drawString(PAGE_MARGIN, y, FOOTER_TEXT)
        canvas.setFillColor(AUOUR_NAVY)
        canvas.setFont(_FONT_SANS_SEMI, 7.1)
        canvas.drawRightString(letter[0] - PAGE_MARGIN, y, "Auour Investments")
        canvas.restoreState()

    doc.build(story, onFirstPage=add_footer, onLaterPages=add_footer)
    return buf.getvalue()
